### ISSUE TITLE
有几个小bug想请教一下

### ISSUE THREAD

**Issue by zybqdm** [JefferyXZF/OnlineBookStore#5]
@JefferyXZF 您好，在使用主页搜索功能的时候，点击搜索之后没有结果，并且控制台会报图三所示的信息，文件目录没有改过；在使用后台的图书管理功能时，点击图书管理时，控制台会报图一中的第一条信息，选择一级分类之后，不能加载相应二级分类，同时控制台出现图一中的第二条信息；另：如果是在谷歌浏览器中，后台的图书管理界面如图二所示，这个问题在换成ie浏览器之后可以正常显示，但是同样存在前面提到的问题。
![图一](https://user-images.githubusercontent.com/62492017/77624007-1b210c80-6f7c-11ea-8406-9ae06e955798.png)

![图二](https://user-images.githubusercontent.com/62492017/77625099-ee6df480-6f7d-11ea-91d1-eb4aa96cee94.png)
![图三](https://user-images.githubusercontent.com/62492017/77625254-37be4400-6f7e-11ea-8882-3e4ae3a17854.png)

**Comment by WebJeffery** [comment]
这个项目我是负责前端部分，很久不看忘了差不多了，看了你截图状态码404，可能是你本地路径访问不到，自己需要调试一下，这个项目只做参考
